apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sonarr.fullname" . }}-deployment
  labels:
    app: sonarr
  {{- include "sonarr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: sonarr
    {{- include "sonarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: sonarr
      {{- include "sonarr.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: {{ .Values.deployment.sonarr.image.repository }}:{{ .Values.deployment.sonarr.image.tag
          | default .Chart.AppVersion }}
        name: sonarr
        ports:
        - containerPort: 8989
        resources: {{- toYaml .Values.deployment.sonarr.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /config
          name: sonarr-config
        - mountPath: /mnt/
          name: media-pv-data
      nodeSelector:
        app: mediabox
      volumes:
#      - name: sonarr-config
#        persistentVolumeClaim:
#          claimName: sonarr-config
      - name: sonarr-config
        hostPath:
           path: /config/sonarr
      - name: media-pv-data
        persistentVolumeClaim:
          claimName: media-pv-pvc-claim