apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sonarr.fullname" . }}-ingress
  labels:
  {{- include "sonarr.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
    nginx.org/client-max-body-size: "0"
    nginx.org/proxy-connect-timeout: 600s
    nginx.org/proxy-read-timeout: 600s
spec:
  rules:
  - host: sonarr.jplex.xyz
    http:
      paths:
      - backend:
          service:
            name: sonarr-service
            port:
              number: 8989
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - sonarr.jplex.xyz
    secretName: sonarr-tls