apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ombi.fullname" . }}-statefulset
  labels:
    app: ombi
    {{- include "ombi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:
      app: ombi
      {{- include "ombi.selectorLabels" . | nindent 6 }}
  serviceName: ombi-service
  template:
    metadata:
      labels:
        app: ombi
        {{- include "ombi.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: {{ .Values.statefulset.ombi.image.repository }}:{{ .Values.statefulset.ombi.image.tag
          | default .Chart.AppVersion }}
        name: ombi
        ports:
        - containerPort: 3579
          name: ombi
        volumeMounts:
        - mountPath: /config
          name: ombi-config
      terminationGracePeriodSeconds: 10
      volumes:
      - name: ombi-config
        persistentVolumeClaim:
          claimName: ombi-config
