apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sabnzbd.fullname" . }}-deployment
  labels:
    app: sabnzbd
  {{- include "sabnzbd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: sabnzbd
    {{- include "sabnzbd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: sabnzbd
      {{- include "sabnzbd.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: {{ .Values.deployment.sabnzbd.image.repository }}:{{ .Values.deployment.sabnzbd.image.tag
          | default .Chart.AppVersion }}
        name: sabnzbd
        ports:
        - containerPort: 8080
        resources: {{- toYaml .Values.deployment.sabnzbd.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /config
          name: sabnzbd-config
        - mountPath: /mnt/
          name: media-pv-data
      nodeSelector:
        app: sonarr
      volumes:
      - name: sabnzbd-config
        persistentVolumeClaim:
          claimName: sabnzbd-config-pvc
      - hostPath:
          path: /mnt
        name: mnt
      - name: media-pv-data
        persistentVolumeClaim:
          claimName: media-pv-claim