apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "heimdall.fullname" . }}-deployment
  labels:
    app: heimdall
  {{- include "heimdall.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: heimdall
    {{- include "heimdall.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: heimdall
      {{- include "heimdall.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: {{ .Values.deployment.heimdall.image.repository }}:{{ .Values.deployment.heimdall.image.tag
          | default .Chart.AppVersion }}
        name: heimdall
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: heimdall-config
      nodeSelector:
        name: node4
      volumes:
      - name: heimdall-config
        persistentVolumeClaim:
          claimName: heimdall-config