---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv-volume
  labels:
    type: local
    pv.beta.kubernetes.io/gid: "abc"
spec:
  storageClassName: manual
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi