apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "radarr.fullname" . }}-config-pvc
  labels:
  {{- include "radarr.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
  storageClassName: manual