apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radarr.fullname" . }}-deployment
  labels:
    app: radarr
  {{- include "radarr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: radarr
    {{- include "radarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: radarr
      {{- include "radarr.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: {{ .Values.deployment.radarr.image.repository }}:{{ .Values.deployment.radarr.image.tag
          | default .Chart.AppVersion }}
        name: radarr
        ports:
        - containerPort: 7878
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: radarr-config
        - mountPath: /mnt/
          name: media-pv-data
      nodeSelector:
        app: mediabox
      volumes:
      - name: radarr-config
        persistentVolumeClaim:
          claimName: radarr-config-pvc
      - name: media-pv-data
        persistentVolumeClaim:
          claimName: media-pv-claim