apiVersion: v1
kind: Service
metadata:
  name: {{ include "radarr.fullname" . }}-service
  labels:
  {{- include "radarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: radarr
  {{- include "radarr.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.service.ports | toYaml | nindent 2 -}}