apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "radarr.fullname" . }}-statefulset
  labels:
    app: radarr
  {{- include "radarr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:
      app: radarr
      {{- include "radarr.selectorLabels" . | nindent 6 }}
  serviceName: radarr-service
  template:
    metadata:
      labels:
        app: radarr
        {{- include "radarr.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: {{ .Values.statefulset.radarr.image.repository }}:{{ .Values.statefulset.radarr.image.tag | default .Chart.AppVersion }}
        name: radarr
        ports:
        - containerPort: 7878
          name: radarr
        volumeMounts:
        - mountPath: /config
          name: radarr-config
        - mountPath: /mnt/
          name: media-pv-data
      nodeSelector:
        app: {{ .Values.statefulset.radarr.nodeSelector.app }}
      terminationGracePeriodSeconds: 10
      volumes:
      - name: radarr-config
        persistentVolumeClaim:
           claimName: radarr-config
      - name: media-pv-data
        persistentVolumeClaim:
          claimName: media-pv-pvc-claim