statefulset:
  radarr:
    nodeSelector:
      app: mediabox
    image:
      repository: linuxserver/radarr
      tag: latest
  replicas: 1
service:
  ports:
  - port: 7878
    protocol: TCP
    targetPort: 7878
  type: ClusterIP
ingress:
  rules:
    host: radarr.yourservice.xyz