apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "plex.fullname" . }}-server
  labels:
    name: plex-server
  {{- include "plex.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      name: plex-server
    {{- include "plex.selectorLabels" . | nindent 6 }}
  serviceName: plex-server
  template:
    metadata:
      labels:
        name: plex-server
      {{- include "plex.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: PLEX_UID
          value: "911"
        - name: PLEX_GID
          value: "911"
        - name: VERSION
          value: docker
        - name: UMASK_SET
          value: "022"
        - name: TZ
          value: Europe/Berlin
        image: {{ .Values.server.plexServer.image.repository }}:{{ .Values.server.plexServer.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 5
          tcpSocket:
            port: 32400
        name: plex-server
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: plex-config
        - mountPath: /transcode
          name: plex-transcode
        - mountPath: /data
          name: media
      hostNetwork: true
#      nodeSelector:
#        app: mediabox
      volumes:
      - name: plex-config
        persistentVolumeClaim:
          claimName: plex-config
      - name: plex-transcode
        hostPath:
          path: /mnt/local/transcode
      - hostPath:
          path: /mnt/unionfs/Media
        name: media
