apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "media-pv-pvc.fullname" . }}-claim
  labels:
  {{- include "media-pv-pvc.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 400Gi
  storageClassName: manual