apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "media-pv-pvc.fullname" . }}-volume
  labels:
    pv.beta.kubernetes.io/gid: abc
    type: local
  {{- include "media-pv-pvc.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 400Gi
  hostPath:
    path: /mnt/
  storageClassName: manual